server:
  port: 9095
  address: 0.0.0.0

spring:
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/soul?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 229927
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: dailyredis.webuy.ai
    port: 6379
    password: xxzgredis
    database: 14

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml


soul:

  sync:
#    websocket:
#        enabled : true
    zookeeper:
        url: dailyzk.webuy.ai:7005
        sessionTimeout: 5000
        connectionTimeout: 2000
#    http:
#      enabled: true
#    nacos:
#      url: localhost:8848
#      namespace: 1c10d748-af86-43b9-8265-75f487d20c6c
#      acm:
#        enabled: false
#        endpoint: acm.aliyun.com
#        namespace:
#        accessKey:
#        secretKey:


logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.dromara.soul.bonuspoint: info
    org.dromara.soul.lottery: info
    org.dromara.soul: info
